language: r
cache: packages
dist: trusty
sudo: required

env:
  global:
  - MAKEFLAGS="-j 2"
  
addons:
apt:
  sources:
     - sourceline: 'ppa:opencpu/jq'
     - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
  packages:
     - libprotobuf-dev
     - protobuf-compiler
     - libv8-dev
     - libjq-dev
     - libudunits2-dev
     - libproj-dev
     - libgeos-dev
     - libgdal-dev
     - libnetcdf-dev
     - libprotoc-dev
     - r-cran-ncdf4
   
install:
  - R -e "install.packages('remotes')"
  - R -e "install.packages('spDataLarge', repos = 'https://nowosad.github.io/drat/', type = 'source')"
  - R -e "remotes::install_github('geocompr/geocompkg')"

script:
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
